version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3 # Сохраняем БД на сервере
      - static_volume:/app/static
      - media_volume:/app/MEDIA
    environment:
      - DEBUG=0
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/MEDIA
    depends_on:
      - backend

volumes:
  static_volume:
  media_volume: