# Generated by Django 6.0.2 on 2026-02-16 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('surname', models.CharField()),
                ('patronymic', models.CharField(blank=True)),
                ('login', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField()),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client')),
            ],
        ),
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('weight', models.IntegerField()),
                ('ingredients', models.CharField()),
                ('production_date', models.DateTimeField()),
                ('amount_avaliable', models.IntegerField(default=0)),
                ('pic', models.ImageField(upload_to='goods')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.good')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('declined', 'Отказано')])),
                ('reason_for_cancellation', models.CharField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.good')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.myuser')),
            ],
        ),
    ]
