# Generated by Django 6.0 on 2026-02-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_good_description_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cold', 'Холодные закуски'), ('hot', 'Горячие закуски'), ('main', 'Основные блюда'), ('soup', 'Супы'), ('sweet', 'Десерты'), ('drinks', 'Напитки'), ('bar', 'Барная карта')], unique=True),
        ),
    ]
