# Generated by Django 6.0.2 on 2026-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
