# Generated by Django 6.0.2 on 2026-05-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myuser_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cold', 'Холодные закуски'), ('hot', 'Горячие закуски'), ('main', 'Основные блюда'), ('soup', 'Супы'), ('sweet', 'Десерты'), ('drinks', 'Напитки'), ('bar', 'Барная карта')], max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='good',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='good',
            name='ingredients',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='good',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='login',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('client', 'Клиент'), ('admin', 'Администратор')], default='client', max_length=255),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='surname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='reason_for_cancellation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('confirmed', 'Подтвержден'), ('canceled', 'Отменен'), ('declined', 'Отказано')], max_length=255),
        ),
    ]
